// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVSM6jCpu19t7gEL7v7d50VFf5W6WJYM',
    appId: '1:326317025776:web:17fe11695fc32ded06d535',
    messagingSenderId: '326317025776',
    projectId: 'mcprojecta1',
    authDomain: 'mcprojecta1.firebaseapp.com',
    storageBucket: 'mcprojecta1.firebasestorage.app',
    measurementId: 'G-59FFL6JNFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfkNcPBu_cNCRyWnbCwOfAHghBneKf3s',
    appId: '1:326317025776:android:816071c14db9bde406d535',
    messagingSenderId: '326317025776',
    projectId: 'mcprojecta1',
    storageBucket: 'mcprojecta1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1CFrBVM2S2BBR3apSESUUYppUUbSugk',
    appId: '1:326317025776:ios:c03fb3da2cdd27e506d535',
    messagingSenderId: '326317025776',
    projectId: 'mcprojecta1',
    storageBucket: 'mcprojecta1.firebasestorage.app',
    iosBundleId: 'com.example.mcSemesterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1CFrBVM2S2BBR3apSESUUYppUUbSugk',
    appId: '1:326317025776:ios:c03fb3da2cdd27e506d535',
    messagingSenderId: '326317025776',
    projectId: 'mcprojecta1',
    storageBucket: 'mcprojecta1.firebasestorage.app',
    iosBundleId: 'com.example.mcSemesterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpVSM6jCpu19t7gEL7v7d50VFf5W6WJYM',
    appId: '1:326317025776:web:67c39e563a49acea06d535',
    messagingSenderId: '326317025776',
    projectId: 'mcprojecta1',
    authDomain: 'mcprojecta1.firebaseapp.com',
    storageBucket: 'mcprojecta1.firebasestorage.app',
    measurementId: 'G-9H4B9536WC',
  );
}
